version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
